platform :ios, '13.0'
use_frameworks!
use_modular_headers!

inhibit_all_warnings!

target 'DKImagePickerControllerDemo' do

  pod 'DKImagePickerController', :path => '../'

  # Pods for DKImagePickerControllerDemo

  target 'DKImagePickerControllerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
      installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
              end
          end
      end
  end
  
end
